CREATE table departments(
	Dno INT PRIMARY key AUTO_INCREMENT,
    Name VARCHAR(20) UNIQUE NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)AUTO_INCREMENT = 10;

CREATE TABLE students(
	Sid INT PRIMARY KEY AUTO_INCREMENT,
    Fname VARCHAR(20) NOT NULL,
    Mname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL,
    Email VARCHAR(30) UNIQUE NOT NULL,
    Phone CHAR(11) UNIQUE NOT NULL,
    Address VARCHAR(100) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Dno INT NOT NULL,

    CONSTRAINT departments_fk
        FOREIGN KEY(Dno) 
        REFERENCES departments(Dno) 
        ON DELETE RESTRICT
        ON UPDATE CASCADE
    
)AUTO_INCREMENT = 1000;

CREATE TABLE courses(
	Cno INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(20) NOT NULL,
    Capacity INT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Dno INT NOT NULL,
    FOREIGN KEY (Dno) REFERENCES departments(Dno) 
        ON DELETE RESTRICT 
        ON UPDATE CASCADE
    
);

CREATE TABLE enrollments(
	SID INT NOT NULL,
    Cno INT NOT NULL,
    Term VARCHAR(10) NOT NULL, 
    Enrolled_at DATE NOT NULL,
    Grade VARCHAR(10) DEFAULT 'Pending',
    
    -- Foreign key to students
    FOREIGN KEY (Sid) REFERENCES students(Sid)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    
    -- foreign key to courses
    FOREIGN KEY (Cno) REFERENCES courses(Cno)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    
    PRIMARY KEY(Sid, Cno, Term)
);

CREATE TABLE instructors(
	Id INT PRIMARY KEY AUTO_INCREMENT,
    Fname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL,
    Email VARCHAR(30) UNIQUE NOT NULL,
    Phone CHAR(11) UNIQUE NOT NULL,
    Status ENUM('Available', 'Unavailable') NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Dno INT NOT NULL,
    
    FOREIGN KEY (Dno) REFERENCES departments(Dno)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
)AUTO_INCREMENT = 100;

CREATE TABLE teaching(
    Instructor_id INT NOT NULL,
    Cno INT NOT NULL,
    Term VARCHAR(10) NOT NULL,
    
    FOREIGN KEY (Instructor_id) REFERENCES instructors(Id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    
    FOREIGN KEY (Cno) REFERENCES courses(Cno)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    
    PRIMARY KEY (Instructor_id, Cno, Term)
);